const initData = [
    {
        id: 'HhuxV',
        idExt: 'HhuxV.zip',
        time: '02:47',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'oHYBG',
        idExt: 'oHYBG.zip',
        time: '02:49',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'Os82R',
        idExt: 'Os82R.zip',
        time: '02:49',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: '0tnpP',
        idExt: '0tnpP.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'eP8aq',
        idExt: 'eP8aq.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'vXwyY',
        idExt: 'vXwyY.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'Puxl3',
        idExt: 'Puxl3.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'hosxm',
        idExt: 'hosxm.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 's174Y',
        idExt: 's174Y.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'XKwpA',
        idExt: 'XKwpA.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: '1xi5i',
        idExt: '1xi5i.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'pD7FB',
        idExt: 'pD7FB.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'emcJZ',
        idExt: 'emcJZ.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
    {
        id: 'pcYg-',
        idExt: 'pcYg-.zip',
        time: '02:50',
        name: 'userText.txt',
        type: 'doc',
    },
];

export default initData;
