const initData = [
    {
        id: 'R4LrK',
        idExt: 'R4LrK.png',
        time: '00:59',
        name: 'Снимок экрана 2021-08-05 в 13.14.41.png',
    },
    {
        id: 'aU86F',
        idExt: 'aU86F.js',
        time: '01:00',
        name: 'jest.config.js',
    },
    {
        id: 'Fmbus',
        idExt: 'Fmbus.txt',
        time: '17:02',
        name: 'userText.txt',
    },
    {
        id: 'vilh0',
        idExt: 'vilh0.txt',
        time: '17:02',
        name: 'userText.txt',
    },
    {
        id: 'yZmcM',
        idExt: 'yZmcM.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'zAqdg',
        idExt: 'zAqdg.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '5DvAC',
        idExt: '5DvAC.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'gB_Xk',
        idExt: 'gB_Xk.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '4SKE_',
        idExt: '4SKE_.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'is7lZ',
        idExt: 'is7lZ.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '4WSYn',
        idExt: '4WSYn.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'apoOY',
        idExt: 'apoOY.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'rDgYI',
        idExt: 'rDgYI.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '2_3B8',
        idExt: '2_3B8.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'qhdDV',
        idExt: 'qhdDV.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'Zh5Lm',
        idExt: 'Zh5Lm.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'uFS98',
        idExt: 'uFS98.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'G4wMr',
        idExt: 'G4wMr.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '0fbXf',
        idExt: '0fbXf.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'JAT-7',
        idExt: 'JAT-7.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'IaaEx',
        idExt: 'IaaEx.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '4K90I',
        idExt: '4K90I.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '-HJ0T',
        idExt: '-HJ0T.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: 'EllOm',
        idExt: 'EllOm.txt',
        time: '17:03',
        name: 'userText.txt',
    },
    {
        id: '5PRo_',
        idExt: '5PRo_.mp3',
        time: '17:06',
        name: 'bensound-goinghigher.mp3',
    },
    {
        id: 'Y2jyl',
        idExt: 'Y2jyl.mp4',
        time: '17:06',
        name: 'Landscape - 757.mp4',
    },
];

export default initData;
